name: pawellak_portfolio
description: "Project about some part of my life."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  components_library:
    path: packages/components/library

  feature_about_me:
    path: packages/features/about_me
  feature_settings:
    path: packages/features/settings
  feature_project_list:
    path: packages/features/project_list
  feature_curriculum_vitae:
    path: packages/features/curriculum_vitae

#  flutter_native_splash: ^2.4.6
#  flutter_launcher_icons: ^0.14.4
#  rename_app: ^1.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: 2.5.4
  injectable_generator: 2.7.0
  json_serializable: 6.9.5

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
    - assets/logo/
    - assets/lottie/
    - assets/features/project_list/images/
    - assets/features/project_list/data/

#flutter_native_splash:
#  color: "#012f80"
#  image: assets/images/splash.png
#  color_dark: "#012f80"
#  image_dark: assets/images/splash.png
#  android_12:
#    image: assets/images/splash_a12.png
#    icon_background_color: "#012f80"
#    image_dark: assets/images/splash_a12.png
#    icon_background_color_dark: "#012f80"
#  ios: true
#  web: true
#
#flutter_launcher_icons:
#  image_path: "assets/logo/logo.png"
#  image_path_ios: "assets/logo/logo.png"
#  adaptive_icon_foreground: "assets/logo/icon_foreground.png"
#  android: true
#  ios: true
#  adaptive_icon_background: "#012f80"
#  remove_alpha_ios: true
#  web:
#    generate: true
#    image_path: "assets/logo/logo.png"
#    background_color: "#012f80"
#    theme_color: "#012f80"
