name: pawellak_portfolio
description: "Project about some part of my life."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  components_library:
    path: packages/components/library
  feature_about_me:
    path: packages/features/about_me
  feature_weather:
    path: packages/features/weather
  feature_settings:
    path: packages/features/settings
  feature_project_list:
    path: packages/features/project_list

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: 2.6.2
  build_runner: 2.4.14
  json_serializable: 6.9.0
