name: components_core
description: Components Core package.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # State Management & Dependency Injection
  flutter_bloc: 9.0.0
  get_it: 8.2.0
  injectable: 2.5.1
  equatable: 2.0.7
  provider: 6.1.5+1

  # Navigation
  go_router: 16.1.0

  # Firebase
  firebase_analytics: 11.5.2
  firebase_crashlytics: 4.3.9

  # Data & Serialization
  json_annotation: 4.9.0
  shared_preferences: 2.5.3

  # Networking
  dio: 5.9.0

  # Localization
  easy_localization: 3.0.8

  # Utilities
  collection: 1.19.1
  logger: 2.6.1
  url_launcher: 6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: 2.5.4
  injectable_generator: 2.7.0
  json_serializable: 6.9.5