name: components_core
description: Components Core package.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.0.0
  firebase_analytics: ^11.5.2
  firebase_crashlytics: ^4.3.9
  logger: ^2.6.1
  injectable: ^2.5.1
  go_router: ^16.1.0
  equatable: ^2.0.7
  shared_preferences: ^2.5.3
  easy_localization: ^3.0.8

dev_dependencies:
  injectable_generator: any
  build_runner: any
  json_serializable: any