name: feature_about_me
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  components_library:
    path: ../../components/library

dev_dependencies:
  build_runner: any
  injectable_generator: any
  retrofit_generator: any
  json_serializable: any
