name: feature_project_list
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  components_library:
    path: ../../components/library

dev_dependencies:
  injectable_generator: any
  json_serializable: ^6.9.5
  json_annotation: any
  build_runner: any
