name: components_library
description: Components Library package.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  components_core:
    path: ../core

  # UI & Styling
  another_flushbar: 1.12.30
  google_fonts: 6.2.1
  lottie: 3.3.1
  shimmer: 3.0.0
  flutter_widget_from_html_core: 0.16.0
  auto_size_text: 3.0.0
  fluentui_system_icons: 1.1.273
  flutter_layout_grid: 2.0.8
  font_awesome_flutter: 10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: 2.5.4
  injectable_generator: 2.7.0
  json_serializable: 6.9.5
